FROM mysql:latest

# COPY mlite_db.sql .

RUN pwd

ARG MYSQL_DATABASE=mlite_db
ARG MYSQL_USER=mlite_db
ARG MYSQL_PASSWORD=mlite_db
ARG MYSQL_ROOT_PASSWORD=iamgroot

ENV MYSQL_DATABASE=$MYSQL_DATABASE
ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

COPY mlite_db.sql /home/

EXPOSE 3306